# Generated by Django 5.1 on 2024-10-05 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myBlog', '0002_alter_blogs_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='slug',
            field=models.SlugField(max_length=255),
        ),
    ]
