# Generated by Django 5.1 on 2024-10-05 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myBlog', '0003_alter_blogs_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='slug',
            field=models.SlugField(default=123, max_length=255),
            preserve_default=False,
        ),
    ]
