# Generated by Django 5.1 on 2024-10-11 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myBlog', '0004_author_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='fullname',
            field=models.CharField(default=1, help_text='Enter you full name', max_length=100),
            preserve_default=False,
        ),
    ]
